version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: financial_advisor_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/enable-vector.sql:/docker-entrypoint-initdb.d/enable-vector.sql
    command: postgres -c shared_preload_libraries=vector

volumes:
  postgres_data: